name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Copy Files to Server
      run: |
        sshpass -p "${{ secrets.SERVER_PASS }}" scp -o StrictHostKeyChecking=no -r * root@${{ secrets.SERVER_HOST }}:/home/root/frontend

    - name: SSH into Server and Build Docker Image
      run: |
        sshpass -p "${{ secrets.SERVER_PASS }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} << 'EOF'
        cd /home/root/frontend
        docker build -t frontend:latest .
        docker stop frontend || true
        docker rm frontend || true
        docker run -d --name frontend -p 8000:8000 frontend:latest
        EOF
